from abc import ABC, abstractmethod
from src.domain.value_objects.token_payload import TokenPayload


class TokenService(ABC):
    @abstractmethod
    def create_access_token(self, payload: TokenPayload) -> str: ...
    @abstractmethod
    def create_refresh_token(self, payload: TokenPayload) -> str: ...
    @abstractmethod
    def decode_token(self, token: str) -> TokenPayload: ...
    @abstractmethod
    def revoke_token(self, jti: str) -> None: ...
    @abstractmethod
    def is_revoked(self, jti: str) -> bool: ...
