from abc import ABC, abstractmethod
from typing import Optional
from src.domain.entities.user import User


class UserRepository(ABC):
    @abstractmethod
    def save(self, user: User) -> User: ...
    @abstractmethod
    def find_by_id(self, user_id: str) -> Optional[User]: ...
    @abstractmethod
    def find_by_username(self, username: str) -> Optional[User]: ...
    @abstractmethod
    def find_by_email(self, email: str) -> Optional[User]: ...
    @abstractmethod
    def list_all(self, skip: int = 0, limit: int = 100) -> list[User]: ...
    @abstractmethod
    def delete(self, user_id: str) -> None: ...
    @abstractmethod
    def count(self) -> int: ...
